### MPA ASIA PROJECT - OBIS ###
### Generate alternative shapefiles of the study area ###

# Modified from MPA Europe code by s.principe@unesco.org
# For Anemonefish and Anemone Host SDM/HSM and Larval Dispersal
# May 2024 - [Your Name]

# Load packages ----
# Spatial manipulation
library(sf)
library(terra)
library(tidyverse)
# Other/visualization
library(ggplot2)
library(mapview)
# Settings
sf_use_s2(FALSE)

# Define version
version <- 1 # Update when making significant changes

# Load study area shapefile (generated by study_area_asia.R) ----
st.area <- read_sf(paste0("data/shapefiles/mpa_asia_starea_v", version, ".shp"))

# Produce alternative shapefiles ----

# 1. Simplified shapefile for simpler maps, illustrations, etc. ----
st.area.simp <- st_simplify(st.area, dTolerance = 0.1) # Adjust dTolerance as needed
plot(st.area.simp)

st_write(st.area.simp, paste0("data/shapefiles/mpa_asia_starea_simple_v", version, ".shp"), delete_layer = TRUE)

# 2. Reproject for a suitable projection (e.g., WGS 84 / Pseudo-Mercator - EPSG:3857) ----
# You might need to choose a different projection based on your specific needs.
# EPSG:3857 is commonly used for web mapping.
st.area.rep <- st_transform(st.area, "EPSG:3857")
plot(st.area.rep)

st_write(st.area.rep,  paste0("data/shapefiles/mpa_asia_starea_prj_v", version, ".shp"), delete_layer = TRUE)

# 3. Generate extended study area (for SDMs) ----
# This creates a larger area around your study area, which can be useful for SDMs
# to account for species potentially occurring just outside the defined boundaries.

# Get GSHHS shapefile (Global Self-consistent, Hierarchical, High-resolution Geography Database)
if (!file.exists("data/gshhg-shp-2.3.7.zip") & !dir.exists("data/gshhg-shp-2.3.7")) {
  download.file("https://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip",
                "data/gshhg-shp-2.3.7.zip")
  unzip("data/gshhg-shp-2.3.7.zip", exdir = "data/gshhg-shp-2.3.7/")
}

borders <- vect("data/gshhg-shp-2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp")

# Get a base raster in the resolution that will be used on the project (example: 0.05 degrees)
base <- rast(resolution = 0.05) # You can adjust the resolution
base[] <- 1

# Get the extent of the study area to be used later for cropping
st.area.ext <- as.polygons(ext(st.area))
st_crs(st.area.ext) <- st_crs(st.area)

# Set crs for base and mask
crs(base) <- "EPSG:4326"
borders <- project(borders, "EPSG:4326")
base <- mask(base, borders, inverse = T)
plot(base)

# Extend the study area 
# Create an extended bounding box, adding a buffer around the original study area
# The buffer size depends on your assumptions about the species' ranges and dispersal
extended_bbox <- st_bbox(st_buffer(st.area.ext, dist = 2)) # Example: 2-degree buffer

# Crop the base raster to this extended bounding box
ext.area <- crop(base, extended_bbox)

# Remove areas not of interest (e.g., other oceans) using mregions
to.remove <- mregions::mr_shp("MarineRegions:goas")
to.remove <- to.remove[to.remove$name %in% c("Arctic Ocean", "Southern Ocean", 
                                             "South Atlantic Ocean", "Indian Ocean"),]
to.remove <- st_as_sf(to.remove)
ext.area <- mask(ext.area, vect(to.remove), inverse = T)

# Convert to polygons and sf object
ext.area <- as.polygons(ext.area)
ext.area <- st_as_sf(ext.area)

# Save
st_write(ext.area,  paste0("data/shapefiles/mpa_asia_extarea_v", version, ".shp"), delete_layer = TRUE)

# 4. Create a 12 nautical mile buffer zone ----
nm12 <- mregions::mr_shp("MarineRegions:eez_12nm", maxFeatures = 3000)

# Intersect with the study area
nm12.area <- st_intersection(nm12, st.area)

# Plot to verify
mapview() + st.area + nm12.area

# You might need to manually remove some areas, similar to the Europe example.
# Inspect the mapview() output and identify any MRGIDs to exclude.
# For example:
# nm12.area <- nm12.area |>
#   filter(!MRGID %in% c(123, 456, 789)) # Replace with actual MRGIDs to remove

# Save final result
st_write(nm12.area, paste0("data/shapefiles/mpa_asia_starea_12nm_v", version, ".shp"), delete_layer = TRUE)